@startuml
[*] --> diffHeader
diffHeader --> fileDefinition
fileDefinition --> contextDefinition
contextDefinition --> fileDiffState
fileDiffState --> multiLineComment
multiLineComment --> fileDiffState
fileDiffState -->contextDefinition
fileDiffState -->fileDefinition
fileDiffState --> [*]


@enduml