@startuml
package mustard {
rectangle git [
 Git Control
]
rectangle cli [
 CommandLineInterpreter / Workflow Factory
]
rectangle "Start Review Workflow" as rstart
rectangle  "Stop Review Workflow" as rsub
rectangle "CommentExtractor" as ce
rectangle "Configuration System" as cs

rectangle bb [
  bitbucket client
]

}

circle "git cli" as gitcli
cli ..> rstart : creates
cli ..> rsub : creates
rstart ..> bb : find PR
rstart  ..> git : checkout & reset
rsub ..> git : 1) reset state
rsub ..> ce : 2) extract comments
rsub ..> bb : 3) push comments

git --( gitcli
bb --( bitbucket
cs ..> git
bb ..> cs
@enduml