@startuml
package mustard {
rectangle git [
 Git Control
]
rectangle cli [
 CommandLineInterpretor
]
rectangle "Review Starter" as rstart
rectangle  "Review submitter" as rsub
rectangle "CommentExtractor" as ce

rectangle bb [
  bitbucket client
]

}
cli ..> rstart : triggger
cli ..> rsub : trigger
cli ..> bb: credentials
rstart ..> bb : find PR
rstart  ..> git : checkout & reset
rsub ..> git : 1) reset state
rsub ..> ce : 2) extract comments
rsub ..> bb : 3) push comments

git --() "git cli"
bb --() bitbucket
@enduml