name: Tests

on:
  push:
    branches:
      - master
      - release
      - updates
  pull_request:
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
      GSL_CXX_STANDARD: 17
      CMAKE_DIR: "${GITHUB_WORKSPACE}/deps"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/rapidjson.deb
          key: deps-rapidjson-1.1.0

      - name: Install rapidjson
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget "https://launchpad.net/ubuntu/+source/rapidjson/1.1.0+dfsg2-3/+build/14513429/+files/rapidjson-dev_1.1.0+dfsg2-3_all.deb" -O rapidjson.deb
          sudo dpkg -i rapidjson.deb

      - name: Install toolchain
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update

      - name: Setup git user
        run: |
          git config --global user.name Tester
          git config --global user.email tester@localhost

      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DRAPIDJSON_BUILD_CXX11=OFF
          make

      - name: Test
        run: |
          ./mustard_tests
        working-directory: build
